### ISSUE TITLE
Please fix file names

### ISSUE THREAD

**Issue by rootkea** [CuriousPICTians/lifematters#5]
Please fix file names. Currently the project is huge pile of mess.
E.g.
1) What does `Dlogin.php` tell you from it's name? Is it doctor login? donor login?
2) `Mreport.php` & `Mreport1.php`
3) `Type1.php` & `Type2.php`
And so on...

**Comment by J0ck88** [comment]
Done

**Comment by rootkea** [comment]
Thanks!
